name: estoque_mobile
description: Sorveteria Camila - Sistema de Controle de Estoque
publish_to: 'none'
version: 1.0.0+1
# FORCE REBUILD: 2026-02-26 19:30 - Dropdown produtos vazio

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.18.1
  image_picker: ^1.0.7
  image_picker_for_web: ^3.0.0
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
