services:
  - type: web
    name: sorveteria-web
    env: static
    buildCommand: |
      # Entrar na pasta do projeto Flutter
      cd estoque_mobile
      # Instalar Flutter
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter doctor
      flutter pub get
      flutter build web --release
    staticPublishPath: estoque_mobile/build/web
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
